# fly.toml file for News Reader App
app = "my-news-reader"   # ← change this to your unique app name

primary_region = "fra"   # ← pick your closest region (e.g., iad, sin, syd, lhr, etc.)

[build]
  dockerfile = "Dockerfile"

# The command Fly runs after starting the container
[processes]
  app = "node index.js"

[env]
  PORT = "8080"
  NODE_ENV = "production"

# Networking
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 0

[mounts]
  source = "data"
  destination = "/app/server/data"
